export const ACTION_TYPES = {
  ADD_DISTANCE_POINT: "ADD_DISTANCE_POINT",
  REMOVE_DISTANCE_POINT: "REMOVE_DISTANCE_POINT",
  SET_DISTANCE_STR: "SET_DISTANCE_STR",
  ADD_MARKER: "ADD_MARKER",
  REMOVE_MARKER: "REMOVE_MARKER",
  SET_MODE: "SET_MODE",
};

export const MODE_TYPES = {
  MARKER: "MARKER",
  DISTANCE: "DISTANCE",
};
