export const ACTION_TYPES = {
  ADD_MEASURE_POINT: "ADD_MEASURE_POINT",
  REMOVE_MEASURE_POINT: "REMOVE_MEASURE_POINT",
  SET_DISTANCE_STR: "SET_DISTANCE_STR",
  ADD_MARKER: "ADD_MARKER",
  REMOVE_MARKER: "REMOVE_MARKER",
  UPDATE_MARKER: "UPDATE_MARKER",
  ADD_RADAR_MARKER: "ADD_RADAR_MARKER",
  REMOVE_RADAR_MARKER: "REMOVE_RADAE_MARKER",
  UPDATE_RADAR_MARKER: "UPDATE_RADAR_MARKER",
  SET_MODE: "SET_MODE",
};

export const MODE_TYPES = {
  MARKER: "MARKER",
  MEASURE_POINT: "MEASURE_POINT",
};
